### PR TITLE
Add easings and Docs

### PR DESCRIPTION
**Pull request by SIMULATAN**
Please add suggestions here

### CODE REVIEW

**Comment by Si1kn** [comment]
no

**Comment by SIMULATAN** [comment]
> 
> 
> no

yes

**Comment by Si1kn** [comment]
no

**Comment by SIMULATAN** [comment]
yes

**Comment by Si1kn** [comment]
_**no**_

**Comment by SIMULATAN** [comment]
***yes***

**Comment by Si1kn** [comment]
_**NO**_

**Comment by SIMULATAN** [comment]
***YES***

**Comment by Si1kn** [comment]
no

**Comment by SIMULATAN** [comment]
yes

**Pull request merged**
